name: Create Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish artifacts
      run: dotnet publish --configuration Release --output ./publish

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ebuild-artifacts-linux
        path: ./publish

    - name: Zip Linux artifacts
      run: zip -r ebuild-${{ github.ref_name }}-linux.zip ./publish

    - name: Generate Release Notes
      id: release_notes
      uses: actions/github-script@v7
      with:
        script: |
          const { data: releases } = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const latestRelease = releases[0];
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed',
            since: latestRelease ? latestRelease.created_at : undefined,
          });
          const releaseNotes = issues
            .filter(issue => !issue.pull_request)
            .map(issue => `- ${issue.title} (#${issue.number})`)
            .join('\n');
          return releaseNotes || 'No closed issues for this release.';

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: ${{ steps.release_notes.outputs.result }}
        draft: false
        prerelease: true
        files: ebuild-${{ github.ref_name }}-linux.zip

  build-and-release-windows:
    runs-on: windows-latest
    needs: build-and-release-linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish artifacts
      run: dotnet publish --configuration Release --output ./publish

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ebuild-artifacts-windows
        path: ./publish

    - name: Zip Windows artifacts
      run: Compress-Archive -Path ./publish/* -DestinationPath ebuild-${{ github.ref_name }}-windows.zip

    - name: Upload Windows Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: ebuild-${{ github.ref_name }}-windows.zip
